name: AI Code Complexity Analyzer v2

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      file_limit:
        description: 'Maximum number of files to analyze'
        required: false
        default: '5'
        type: string

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Find JavaScript files
      id: find_files
      run: |
        # Find all JS files (limit based on input or default to 5)
        LIMIT=${{ github.event.inputs.file_limit || '5' }}
        FILES=$(find . -name "*.js" -type f | head -$LIMIT | tr '\n' ' ')
        echo "files=$FILES" >> $GITHUB_OUTPUT

    - name: Analyze with AI
      run: |
        set -euo pipefail
        # Initialize results file
        echo "# 🤖 AI Code Complexity Analysis" > analysis_results.md
        echo "" >> analysis_results.md
        echo "Generated on: $(date)" >> analysis_results.md
        echo "" >> analysis_results.md
        
        # Analyze each file
        for file in ${{ steps.find_files.outputs.files }}; do
          if [ ! -s "$file" ]; then
            echo "Skipping empty or unreadable file: $file"
            continue
          fi
          echo "Analyzing $file..."
          
          # Debug: show first few lines of file
          echo "First 5 lines of $file:"
          head -n 5 "$file"
          echo "---"
          
          # Create a simple analysis without complex JSON escaping
          echo "Creating analysis for $file..."
          
          # Use a simple approach - write to temp files
          echo "Analyze the code complexity and provide a brief assessment including: complexity score (1-10), main concerns, and improvement suggestions. Be concise." > system_prompt.txt
          echo "Please analyze this JavaScript code for complexity:" > user_prompt.txt
          head -n 50 "$file" >> user_prompt.txt
          
          # Create JSON using printf to avoid escaping issues  
          printf '{"model":"%s","messages":[{"role":"system","content":"%s"},{"role":"user","content":"%s"}],"temperature":0.3,"max_tokens":200}' \
            "${{ secrets.OPENAI_MODEL }}" \
            "$(cat system_prompt.txt)" \
            "$(cat user_prompt.txt | tr '\n' ' ' | sed 's/"/\\"/g')" > request.json
          
          # Call API
          ANALYSIS=$(curl -s -X POST "${{ secrets.OPENAI_API_ENDPOINT }}/v1/chat/completions" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d @request.json | jq -r '.choices[0].message.content // "Analysis failed"')
          # Append to results
          echo "## File: \`$file\`" >> analysis_results.md
          echo "" >> analysis_results.md
          echo "$ANALYSIS" >> analysis_results.md
          echo "" >> analysis_results.md
          echo "---" >> analysis_results.md
          echo "" >> analysis_results.md
        done

    - name: Upload analysis results
      uses: actions/upload-artifact@v4
      with:
        name: ai-analysis
        path: analysis_results.md

    - name: Comment on commit (optional)
      if: github.event_name == 'push'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const analysis = fs.readFileSync('analysis_results.md', 'utf8');
          
          // Create a comment on the commit
          await github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: analysis
          });
